### ISSUE TITLE
valid for Godot 3.0?

### ISSUE THREAD

**Issue by pgruenbacher** [kubecz3k/GroupManager#1]

**Comment by pgruenbacher** [comment]
![screenshot from 2017-11-10 18-38-43](https://user-images.githubusercontent.com/3332598/32683073-7c7092b2-c646-11e7-9985-fa93dad25424.png)

**Comment by kubecz3k** [comment]
Hello, thanks for a report I know about this, just I was fixing it already once, and then there was another api breakage and controls started to behave differently one more time :) I will wait around beta with a fix. Also the plugin will be in new repository in 3.0

**Comment by kubecz3k** [comment]
(decided to merge couple smaller plugins into one package)
